// ============================================================================
// ENGLISH WORD FREQUENCY DICTIONARY
// ============================================================================
//
// Top ~5000 most commonly used English words based on corpus frequency data.
// Words in this set should NEVER be considered "rare" or "unique" for
// stylometric fingerprinting purposes — they are normal everyday vocabulary.
//
// This supplements the manually curated COMMON_GAMING_WORDS list in constants.ts
// by providing broad coverage of general English vocabulary that any native
// or fluent speaker might use.
// ============================================================================

/**
 * Set of common English words (5+ characters) that should never be flagged
 * as rare/unique vocabulary. Only includes words with 5+ chars since the
 * rare-word detection already filters out shorter words.
 */
export const COMMON_ENGLISH_WORDS = new Set([
  // --- A ---
  "about", "above", "abuse", "accept", "access", "accident", "account",
  "accuse", "achieve", "across", "action", "active", "activity", "actual",
  "actually", "added", "address", "admit", "adopt", "adult", "advance",
  "advantage", "advice", "advise", "affair", "affect", "afford", "afraid",
  "after", "afternoon", "again", "against", "agent", "agree", "agreement",
  "ahead", "alarm", "album", "alcohol", "alien", "alike", "alive", "alley",
  "allow", "almost", "alone", "along", "already", "alright", "alter",
  "alternative", "although", "always", "amaze", "amazed", "amazing",
  "ambition", "among", "amount", "amuse", "ancient", "anger", "angle",
  "angry", "animal", "ankle", "announce", "annual", "another", "answer",
  "anxiety", "anyone", "anything", "anyway", "anywhere", "apart",
  "apartment", "apology", "appeal", "appear", "apple", "application",
  "apply", "appointment", "appreciate", "approach", "appropriate", "approve",
  "argue", "argument", "arise", "armed", "around", "arrange", "arrest",
  "arrival", "arrive", "arrow", "article", "aside", "asleep", "aspect",
  "assault", "assert", "assess", "asset", "assign", "assist", "associate",
  "assume", "assure", "atmosphere", "attach", "attack", "attempt", "attend",
  "attention", "attitude", "attract", "audience", "author", "authority",
  "automatic", "available", "average", "avoid", "awake", "award", "aware",
  "awful",

  // --- B ---
  "background", "backward", "badge", "badly", "balance", "banana", "barely",
  "bargain", "barrel", "barrier", "baseball", "basic", "basically", "basis",
  "basket", "basketball", "bathroom", "battery", "battle", "beach", "bearing",
  "beautiful", "beauty", "became", "become", "bedroom", "before", "began",
  "begin", "beginning", "behalf", "behave", "behavior", "behind", "being",
  "belief", "believe", "belong", "below", "bench", "beneath", "benefit",
  "berry", "beside", "besides", "better", "between", "beyond", "bible",
  "bicycle", "bigger", "billion", "birth", "birthday", "blade", "blame",
  "blank", "blanket", "blast", "bleed", "blend", "bless", "blind", "block",
  "blood", "board", "boast", "bonus", "border", "bored", "boring", "borrow",
  "bother", "bottle", "bottom", "bought", "bounce", "bound", "brain",
  "branch", "brand", "brave", "bread", "break", "breakfast", "breast",
  "breath", "breathe", "breed", "brick", "bridge", "brief", "bright",
  "brilliant", "bring", "broad", "broke", "broken", "brother", "brown",
  "brush", "bubble", "bucket", "buddy", "budget", "build", "building",
  "bullet", "bunch", "burden", "buried", "burst", "business", "busy",
  "butter", "button", "buyer",

  // --- C ---
  "cabin", "cabinet", "cable", "calculate", "camera", "campaign", "campus",
  "cancel", "cancer", "candidate", "capable", "capacity", "capital",
  "captain", "capture", "carbon", "career", "careful", "carefully", "carry",
  "category", "cattle", "caught", "cause", "celebrate", "celebration",
  "center", "central", "century", "ceremony", "certain", "certainly",
  "chain", "chair", "chairman", "challenge", "chamber", "champion", "chance",
  "change", "channel", "chapter", "character", "charge", "charity", "chart",
  "chase", "cheap", "check", "cheek", "cheese", "chest", "chicken", "chief",
  "child", "childhood", "china", "chips", "chocolate", "choice", "choose",
  "church", "cigarette", "circle", "circumstance", "citizen", "civil",
  "claim", "class", "classic", "classroom", "clean", "clear", "clearly",
  "clever", "client", "climate", "climb", "clinic", "clock", "close",
  "closely", "closer", "closest", "cloth", "clothes", "clothing", "cloud",
  "coach", "coalition", "coast", "coffee", "collapse", "colleague", "collect",
  "collection", "college", "color", "column", "combat", "combination",
  "combine", "comfort", "comfortable", "command", "commander", "comment",
  "commercial", "commission", "commit", "commitment", "committee", "common",
  "communicate", "communication", "community", "companion", "company",
  "compare", "comparison", "compete", "competition", "competitive",
  "complain", "complaint", "complete", "completely", "complex", "complicated",
  "component", "computer", "concentrate", "concentration", "concept",
  "concern", "concerned", "conclude", "conclusion", "condition", "conduct",
  "conference", "confidence", "confident", "confirm", "conflict", "confront",
  "confuse", "confused", "confusion", "connect", "connection", "conscious",
  "consciousness", "consensus", "consequence", "conservative", "consider",
  "considerable", "consideration", "consist", "consistent", "constant",
  "constantly", "constitute", "construction", "consultant", "consumer",
  "consumption", "contact", "contain", "container", "content", "contest",
  "context", "continue", "contract", "contrast", "contribute", "contribution",
  "control", "controversial", "controversy", "conversation", "convert",
  "conviction", "convince", "convinced", "cookie", "cooking", "corner",
  "corporate", "correct", "correspond", "costs", "couch", "could", "council",
  "count", "counter", "country", "countryside", "county", "couple", "courage",
  "course", "court", "cousin", "cover", "coverage", "crack", "craft",
  "crash", "crazy", "cream", "create", "creation", "creative", "creature",
  "credit", "crew", "crime", "criminal", "crisis", "criteria", "critic",
  "critical", "criticism", "cross", "crowd", "crucial", "crush", "cultural",
  "culture", "current", "currently", "curriculum", "customer", "cycle",

  // --- D ---
  "daddy", "daily", "damage", "dance", "danger", "dangerous", "daughter",
  "dealer", "death", "debate", "decade", "decent", "decide", "decision",
  "declare", "decline", "decorate", "decrease", "deeply", "defeat", "defend",
  "defendant", "defense", "defensive", "define", "definitely", "definition",
  "degree", "delay", "deliver", "delivery", "demand", "democracy",
  "democratic", "demonstrate", "demonstration", "dental", "deny", "depart",
  "department", "depend", "dependent", "depending", "depict", "deposit",
  "depression", "deputy", "derive", "describe", "description", "desert",
  "deserve", "design", "designer", "desire", "desperate", "despite",
  "destroy", "destruction", "detail", "detailed", "detect", "determine",
  "develop", "developer", "development", "device", "devote", "dialogue",
  "diamond", "difference", "different", "differently", "difficult",
  "difficulty", "digital", "dimension", "dinner", "direction", "directly",
  "director", "dirty", "disability", "disagree", "disappear", "disappoint",
  "disaster", "discipline", "discount", "discover", "discovery", "discuss",
  "discussion", "disease", "display", "dispute", "distance", "distant",
  "distinct", "distinction", "distinguish", "distribute", "distribution",
  "district", "disturb", "divide", "division", "divorce", "doctor",
  "document", "dollar", "domestic", "dominant", "dominate", "double",
  "doubt", "downtown", "draft", "dramatic", "dramatically", "drawing",
  "dream", "dress", "drink", "drive", "driver", "driving", "drunk",
  "during", "dusty",

  // --- E ---
  "eager", "early", "earth", "easily", "eastern", "eating", "economic",
  "economy", "edition", "editor", "educate", "education", "educational",
  "effect", "effective", "effectively", "efficiency", "efficient", "effort",
  "eight", "either", "elaborate", "elderly", "elect", "election", "electric",
  "electricity", "electronic", "element", "eliminate", "elite", "elsewhere",
  "email", "embarrass", "embrace", "emerge", "emergency", "emission",
  "emotion", "emotional", "emphasis", "emphasize", "empire", "employ",
  "employee", "employer", "employment", "empty", "enable", "encounter",
  "encourage", "enemy", "energy", "enforce", "engage", "engine", "engineer",
  "engineering", "enjoy", "enormous", "enough", "ensure", "enter",
  "enterprise", "entertainment", "enthusiasm", "entire", "entirely",
  "entrance", "entry", "environment", "environmental", "episode", "equal",
  "equally", "equipment", "error", "escape", "especially", "essay",
  "essential", "essentially", "establish", "establishment", "estate",
  "estimate", "evaluate", "evening", "event", "eventually", "every",
  "everybody", "everyday", "everyone", "everything", "everywhere", "evidence",
  "evident", "evil", "evolution", "evolve", "exact", "exactly", "examine",
  "example", "excellent", "except", "exception", "exchange", "excite",
  "excited", "excitement", "exciting", "exclude", "excuse", "execute",
  "executive", "exercise", "exhibit", "exhibition", "exist", "existence",
  "existing", "expand", "expansion", "expect", "expectation", "expense",
  "expensive", "experience", "experiment", "expert", "explain", "explanation",
  "explicit", "explode", "exploit", "exploration", "explore", "explosion",
  "expose", "exposure", "express", "expression", "extend", "extension",
  "extensive", "extent", "external", "extra", "extraordinary", "extreme",
  "extremely",

  // --- F ---
  "fabric", "facial", "facility", "factor", "factory", "faculty", "failure",
  "fairly", "faith", "false", "familiar", "family", "famous", "fancy",
  "fantasy", "farmer", "fascinating", "fashion", "father", "fault",
  "favorite", "feature", "federal", "feedback", "feeling", "fellow",
  "female", "fence", "fewer", "fiction", "field", "fierce", "fight",
  "fighter", "fighting", "figure", "filling", "final", "finally", "finance",
  "financial", "finding", "finger", "finish", "fired", "first", "fishing",
  "fitness", "fixed", "flavor", "flesh", "flexible", "flight", "float",
  "flood", "floor", "flower", "focus", "follow", "following", "football",
  "force", "foreign", "forest", "forever", "forget", "forgive", "formal",
  "format", "former", "formula", "forth", "fortune", "forward", "foster",
  "found", "foundation", "founder", "fourth", "frame", "framework", "freedom",
  "freeze", "french", "frequency", "frequent", "frequently", "fresh",
  "friday", "friend", "friendly", "friendship", "front", "fruit",
  "frustrate", "frustration", "fulfill", "fully", "function", "fundamental",
  "funding", "funny", "furniture", "further", "furthermore", "future",

  // --- G ---
  "gallery", "garden", "garlic", "gather", "gender", "general", "generally",
  "generate", "generation", "genetic", "genius", "genre", "gentle",
  "gentleman", "genuine", "giant", "girlfriend", "given", "glad", "glance",
  "glass", "global", "glory", "gonna", "grade", "gradually", "graduate",
  "grain", "grand", "grandfather", "grandmother", "grant", "grass", "grave",
  "grasp", "grateful", "great", "greatest", "green", "greet", "grocery",
  "ground", "group", "growing", "grown", "growth", "guarantee", "guard",
  "guess", "guest", "guide", "guilty", "guitar",

  // --- H ---
  "habit", "handle", "happen", "happened", "happening", "happiness", "happy",
  "harbor", "hardly", "haven", "having", "headline", "headquarters", "health",
  "healthy", "heard", "hearing", "heart", "heaven", "heavily", "heavy",
  "height", "hello", "helpful", "hence", "heritage", "herself", "highly",
  "himself", "hired", "historian", "historic", "historical", "history",
  "hobby", "holiday", "honest", "honestly", "honor", "hopefully", "horror",
  "horse", "hospital", "hotel", "household", "housing", "however", "human",
  "humor", "hundred", "hungry", "hunter", "hunting", "hurry", "husband",

  // --- I ---
  "ideal", "identify", "identity", "ignore", "illegal", "illness", "illustrate",
  "image", "imagination", "imagine", "immediate", "immediately", "immigrant",
  "immigration", "impact", "implement", "implication", "imply", "import",
  "importance", "important", "impose", "impossible", "impress", "impressed",
  "impression", "impressive", "improve", "improvement", "incident", "include",
  "including", "income", "incorporate", "increase", "increasingly",
  "incredible", "incredibly", "indeed", "independence", "independent",
  "index", "indicate", "individual", "industrial", "industry", "inevitable",
  "infant", "infection", "inflation", "influence", "inform", "information",
  "ingredient", "initial", "initially", "initiative", "injury", "inner",
  "innocent", "innovation", "input", "inquiry", "insert", "inside",
  "insight", "insist", "inspection", "inspiration", "inspire", "install",
  "instance", "instant", "instead", "institution", "institutional",
  "instruction", "instructor", "instrument", "insurance", "intellectual",
  "intelligence", "intelligent", "intend", "intense", "intensity",
  "intention", "interact", "interaction", "interest", "interested",
  "interesting", "internal", "international", "internet", "interpret",
  "interpretation", "intervention", "interview", "introduce", "introduction",
  "invade", "invasion", "invest", "investigate", "investigation",
  "investigator", "investment", "investor", "invisible", "invitation",
  "invite", "involve", "involved", "involvement", "isolate", "issue",
  "itself",

  // --- J ---
  "jacket", "joint", "journal", "journalist", "journey", "judge", "judgment",
  "juice", "junior", "justice", "justify",

  // --- K ---
  "keeps", "kidney", "killing", "kitchen", "knife", "knock", "knowledge",

  // --- L ---
  "label", "labor", "laboratory", "landscape", "language", "laptop", "large",
  "largely", "later", "latest", "latter", "laugh", "laughter", "launch",
  "layer", "leader", "leadership", "leading", "league", "learned",
  "learning", "least", "leather", "leave", "leaving", "lecture", "legal",
  "legend", "legislation", "legitimate", "lemon", "length", "lesson",
  "letter", "level", "liberal", "liberty", "library", "license", "lifestyle",
  "lifetime", "light", "likely", "limit", "limited", "listen", "literally",
  "literary", "literature", "little", "lived", "living", "local", "locate",
  "location", "lonely", "loose", "lover", "lower", "lucky", "lunch",
  "luxury",

  // --- M ---
  "machine", "magazine", "magic", "magnificent", "maintain", "major",
  "majority", "maker", "manage", "management", "manager", "manner",
  "manufacturer", "manufacturing", "margin", "market", "marketing",
  "marriage", "married", "marry", "massive", "master", "match", "material",
  "matter", "mayor", "meaning", "meanwhile", "measure", "measurement",
  "mechanism", "media", "medical", "medication", "medicine", "medium",
  "meeting", "member", "membership", "memory", "mental", "mention", "merely",
  "message", "method", "middle", "might", "military", "million", "minister",
  "minor", "minority", "minute", "miracle", "mirror", "mission", "mistake",
  "mixture", "mobile", "model", "moderate", "modern", "modest", "modify",
  "moment", "monday", "money", "monitor", "month", "monthly", "moral",
  "morning", "mortgage", "mostly", "mother", "motion", "motivation", "motor",
  "mount", "mountain", "mouth", "moved", "movement", "movie", "multiple",
  "murder", "muscle", "museum", "music", "musical", "muslim", "mutual",
  "mystery",

  // --- N ---
  "naked", "narrative", "narrow", "nation", "national", "native", "natural",
  "naturally", "nature", "nearby", "nearly", "necessarily", "necessary",
  "negative", "negotiate", "negotiation", "neighbor", "neighborhood",
  "neither", "nerve", "nervous", "network", "never", "nevertheless",
  "newspaper", "night", "nobody", "noise", "nomination", "normal",
  "normally", "north", "northern", "notable", "nothing", "notice",
  "notion", "novel", "nuclear", "number", "numerous", "nurse",

  // --- O ---
  "object", "objection", "objective", "obligation", "observation", "observe",
  "observer", "obstacle", "obtain", "obvious", "obviously", "occasion",
  "occasionally", "occupation", "occupy", "occur", "ocean", "offense",
  "offensive", "offer", "office", "officer", "official", "often", "online",
  "opening", "operate", "operation", "operator", "opinion", "opponent",
  "opportunity", "oppose", "opposite", "opposition", "option", "orange",
  "order", "ordinary", "organic", "organization", "organize", "orientation",
  "origin", "original", "originally", "other", "others", "otherwise",
  "ought", "ourselves", "outcome", "outdoor", "outer", "output", "outside",
  "outstanding", "overall", "overcome", "overlook", "owner", "ownership",

  // --- P ---
  "package", "paint", "painting", "panel", "panic", "paper", "parent",
  "parking", "particularly", "partly", "partner", "partnership", "party",
  "passage", "passenger", "passing", "passion", "passive", "patient",
  "pattern", "pause", "payment", "peace", "peaceful", "penalty", "pension",
  "people", "pepper", "percentage", "perception", "perfect", "perfectly",
  "perform", "performance", "perhaps", "period", "permanent", "permission",
  "permit", "person", "personal", "personality", "personally", "perspective",
  "phase", "phenomenon", "philosophy", "phone", "photo", "photograph",
  "phrase", "physical", "physically", "piano", "picture", "piece", "pilot",
  "pitch", "pizza", "place", "plain", "plane", "planet", "planning",
  "plant", "plastic", "plate", "platform", "player", "please", "pleasure",
  "plenty", "pocket", "poetry", "point", "pointed", "poison", "police",
  "policy", "political", "politically", "politician", "politics",
  "pollution", "popular", "popularity", "population", "porch", "portion",
  "portrait", "portray", "position", "positive", "possibility", "possible",
  "possibly", "potato", "potential", "potentially", "pound", "poverty",
  "power", "powerful", "practical", "practice", "prayer", "precisely",
  "predict", "prediction", "predominantly", "prefer", "preference",
  "pregnancy", "pregnant", "premium", "preparation", "prepare", "prepared",
  "presence", "present", "presentation", "preserve", "presidency",
  "president", "presidential", "press", "pressure", "presumably", "pretend",
  "pretty", "prevent", "previous", "previously", "price", "pride",
  "primarily", "primary", "prime", "prince", "princess", "principal",
  "principle", "print", "prior", "priority", "prison", "prisoner", "privacy",
  "private", "privately", "prize", "probably", "problem", "procedure",
  "proceed", "process", "produce", "producer", "product", "production",
  "productive", "profession", "professional", "professor", "profile",
  "profit", "program", "progress", "project", "prominent", "promise",
  "promote", "promotion", "proof", "proper", "properly", "property",
  "proportion", "proposal", "propose", "proposed", "prosecutor", "prospect",
  "protect", "protection", "protein", "protest", "proud", "prove",
  "provide", "provider", "province", "provision", "psychological",
  "psychologist", "psychology", "public", "publication", "publicly",
  "publish", "publisher", "pulling", "punch", "punishment", "purchase",
  "purely", "purpose", "pursue", "pursuit", "pushing",

  // --- Q ---
  "qualify", "quality", "quantity", "quarter", "question", "quick",
  "quickly", "quiet", "quietly", "quite", "quote",

  // --- R ---
  "racial", "racism", "radical", "raise", "range", "rapid", "rapidly",
  "rarely", "rating", "ratio", "reach", "react", "reaction", "reader",
  "reading", "ready", "realistic", "reality", "realize", "really",
  "reason", "reasonable", "rebel", "recall", "receive", "recent",
  "recently", "recipe", "recognition", "recognize", "recommend",
  "recommendation", "record", "recording", "recover", "recovery", "recruit",
  "reduce", "reduction", "refer", "reference", "reflect", "reflection",
  "reform", "refugee", "refuse", "regard", "regarding", "regime", "region",
  "regional", "register", "regular", "regularly", "regulation", "reinforce",
  "reject", "relate", "related", "relation", "relationship", "relative",
  "relatively", "release", "relevant", "relief", "religion", "religious",
  "reluctant", "remain", "remaining", "remarkable", "remember", "remind",
  "remote", "removal", "remove", "repeat", "repeatedly", "replace",
  "replacement", "reply", "report", "reporter", "represent",
  "representation", "representative", "reproduce", "republic", "republican",
  "reputation", "request", "require", "requirement", "research",
  "researcher", "resemble", "reservation", "resident", "residential",
  "resign", "resist", "resistance", "resolution", "resolve", "resort",
  "resource", "respond", "response", "responsibility", "responsible", "rest",
  "restaurant", "restore", "restriction", "result", "retain", "retire",
  "retirement", "retreat", "return", "reveal", "revenue", "review",
  "revolution", "rhetoric", "rhythm", "rifle", "right", "river", "robot",
  "romantic", "rough", "roughly", "round", "route", "routine", "royal",
  "rural", "russian",

  // --- S ---
  "sacred", "sacrifice", "safety", "salary", "sample", "sanction",
  "sandwich", "satellite", "satisfaction", "satisfy", "saturday", "sauce",
  "saving", "scale", "scandal", "scared", "scenario", "scene", "schedule",
  "scholar", "scholarship", "school", "science", "scientific", "scientist",
  "scope", "score", "screen", "script", "search", "season", "second",
  "secondary", "secret", "secretary", "section", "sector", "secure",
  "security", "seeking", "segment", "seize", "select", "selection", "seller",
  "senate", "senator", "senior", "sense", "sensitive", "sentence",
  "separate", "separately", "sequence", "series", "serious", "seriously",
  "serve", "server", "service", "session", "settle", "settlement", "seven",
  "several", "severe", "sexual", "shade", "shadow", "shake", "shall",
  "shame", "shape", "share", "sharp", "sheet", "shelf", "shell", "shelter",
  "shift", "shine", "shirt", "shock", "shoot", "shooting", "shopping",
  "shore", "short", "shortage", "shortly", "shoulder", "shout", "shower",
  "sight", "signal", "significant", "significantly", "silence", "silent",
  "silly", "silver", "similar", "similarly", "simple", "simply",
  "simultaneously", "since", "singer", "single", "sister", "situation",
  "skill", "sleep", "slice", "slide", "slight", "slightly", "slowly",
  "small", "smart", "smell", "smile", "smoke", "smooth", "snap", "social",
  "society", "software", "solar", "soldier", "solid", "solution", "solve",
  "somebody", "somehow", "someone", "something", "sometimes", "somewhat",
  "somewhere", "sorry", "sound", "source", "south", "southern", "space",
  "speak", "speaker", "special", "specialist", "specific", "specifically",
  "speech", "speed", "spend", "spending", "spirit", "spiritual", "split",
  "spokesman", "sport", "spread", "spring", "squad", "stable", "staff",
  "stage", "stake", "stand", "standard", "standing", "start", "starting",
  "state", "statement", "station", "status", "steady", "steal", "steel",
  "steep", "stick", "stock", "stomach", "stone", "store", "storm", "story",
  "straight", "strain", "strange", "stranger", "strategic", "strategy",
  "stream", "street", "strength", "strengthen", "stress", "stretch",
  "strict", "strike", "string", "strip", "stroke", "strong", "strongly",
  "structural", "structure", "struggle", "student", "studio", "study",
  "stuff", "stupid", "style", "subject", "submit", "subsequent",
  "substance", "substantial", "succeed", "success", "successful",
  "successfully", "sudden", "suddenly", "suffer", "sufficient", "sugar",
  "suggest", "suggestion", "suicide", "summer", "sunday", "super",
  "supply", "support", "supporter", "suppose", "supposed", "surely",
  "surface", "surgery", "surprise", "surprised", "surprising",
  "surprisingly", "surround", "surrounding", "survey", "survival",
  "survive", "survivor", "suspect", "suspend", "suspicion", "suspicious",
  "sustain", "swallow", "swear", "sweet", "swimming", "swing", "switch",
  "symbol", "sympathy", "symptom", "system",

  // --- T ---
  "table", "tactic", "talent", "target", "taste", "teach", "teacher",
  "teaching", "teammate", "teaspoon", "technical", "technically",
  "technique", "technology", "television", "temperature", "temporary",
  "tenant", "tendency", "tennis", "tension", "terms", "terrible",
  "territory", "terror", "terrorism", "terrorist", "thank", "thanks",
  "thanksgiving", "theater", "theme", "themselves", "theory", "therapy",
  "there", "thereby", "therefore", "thick", "thing", "things", "think",
  "thinking", "third", "thoroughly", "those", "though", "thought",
  "thousand", "threat", "threaten", "three", "throat", "through",
  "throughout", "throw", "thursday", "ticket", "tight", "tired", "tissue",
  "title", "today", "together", "tomorrow", "tonight", "topic", "total",
  "totally", "touch", "tough", "tourism", "tourist", "tournament", "toward",
  "towards", "tower", "track", "trade", "tradition", "traditional",
  "traffic", "trail", "train", "training", "transfer", "transform",
  "transformation", "transition", "translate", "translation", "transport",
  "transportation", "travel", "treat", "treatment", "treaty", "tremendous",
  "trend", "trial", "tribe", "trick", "trigger", "trillion", "triumph",
  "troop", "tropical", "trouble", "truck", "truly", "trust", "truth",
  "tuesday", "tunnel", "twice", "typical", "typically",

  // --- U ---
  "ugly", "ultimate", "ultimately", "unable", "uncle", "under",
  "undergo", "underlying", "understand", "understanding", "unemployment",
  "unfair", "unfortunately", "unhappy", "uniform", "union", "unique",
  "united", "unity", "universal", "universe", "university", "unknown",
  "unless", "unlike", "unlikely", "until", "unusual", "upper", "upset",
  "urban", "urge", "usual", "usually", "utility",

  // --- V ---
  "vacation", "valley", "valuable", "value", "variable", "variation",
  "variety", "various", "vast", "vehicle", "venture", "version", "versus",
  "veteran", "victim", "victory", "video", "viewer", "village",
  "violation", "violence", "violent", "virtual", "virtue", "visible",
  "vision", "visit", "visitor", "visual", "vital", "voice", "volume",
  "voluntary", "volunteer", "voter", "voting", "vulnerable",

  // --- W ---
  "wages", "waiting", "wake", "walk", "walking", "wallet", "wander",
  "warning", "wash", "waste", "watch", "watching", "water", "wave",
  "weakness", "wealth", "weapon", "weather", "website", "wedding",
  "wednesday", "weekend", "weekly", "weigh", "weight", "weird",
  "welcome", "welfare", "western", "whatever", "wheat", "wheel",
  "whenever", "whereas", "wherever", "whether", "while", "whisper",
  "white", "whole", "whose", "widely", "willing", "window", "winner",
  "winter", "wisdom", "woman", "women", "wonder", "wonderful", "wooden",
  "worker", "working", "workout", "workplace", "works", "workshop",
  "world", "worried", "worry", "worse", "worship", "worst", "worth",
  "worthy", "would", "wound", "write", "writer", "writing", "wrong",

  // --- Y ---
  "yard", "yearly", "yellow", "yesterday", "yield", "young", "youngster",
  "yourself", "youth",

  // =========================================================================
  // Additional everyday words commonly seen in casual online chat
  // =========================================================================
  "absolutely", "accident", "account", "afternoon", "agree", "airport",
  "allowed", "annoying", "answer", "anymore", "apartment", "apologize",
  "apparently", "appetite", "appointment", "appreciate", "area", "asleep",
  "assume", "attention", "awesome",
  "backyard", "banana", "basically", "bathroom", "battery", "beautiful",
  "bedroom", "believe", "birthday", "bored", "boring", "bottle", "boyfriend",
  "breakfast", "breath", "broken", "brother", "budget", "building",
  "burned", "cabinet", "calendar", "careful", "carpet", "ceiling",
  "cellphone", "certainly", "changed", "channel", "charge", "chicken",
  "chocolate", "cleaning", "clearly", "climate", "closet", "coffee",
  "comfortable", "coming", "comment", "community", "company", "complain",
  "complete", "completely", "concern", "confused", "connection",
  "consider", "control", "conversation", "cooking", "corner",
  "couch", "counter", "country", "couple", "cousin", "coworker",
  "customer", "daughter", "decide", "definitely", "delivery",
  "dentist", "describe", "deserve", "design", "device", "different",
  "difficult", "dinner", "direction", "dirty", "disappear",
  "discover", "distance", "doctor", "doesn", "dollar", "double",
  "downstairs", "drawer", "dress", "driving", "during",
  "either", "electric", "elevator", "email", "emergency",
  "enjoy", "enough", "entire", "envelope", "errand", "especially",
  "everybody", "everyday", "everyone", "everything", "everywhere",
  "exactly", "example", "excellent", "except", "excited",
  "exciting", "exercise", "expect", "expensive", "experience",
  "explain", "extra", "extremely",
  "family", "fantastic", "favorite", "feeling", "finally",
  "finger", "finish", "finished", "flower", "football",
  "forget", "forgot", "forward", "found", "friend", "front",
  "furniture", "future",
  "garage", "garden", "general", "getting", "girlfriend",
  "glasses", "gotten", "government", "grandma", "grandpa",
  "grateful", "great", "grocery", "ground", "group", "growing",
  "guess", "guilty",
  "hallway", "happened", "happens", "headache", "heard",
  "healthy", "heavy", "herself", "himself", "honestly",
  "horrible", "hospital", "hotel", "house", "however",
  "hundred", "hungry", "hurry", "husband",
  "imagine", "important", "impossible", "improve",
  "include", "incredible", "inside", "instead", "interest",
  "interesting", "internet", "invite",
  "jacket", "jealous", "juice",
  "kitchen", "knock", "knowing",
  "landlord", "laptop", "laundry", "learned", "leaving",
  "lesson", "library", "listen", "living", "local",
  "locked", "longer", "looking", "lucky", "lunch",
  "machine", "manage", "matter", "maybe", "meaning",
  "meeting", "memory", "mention", "message", "middle",
  "million", "minute", "minutes", "mirror", "missing",
  "mistake", "moment", "money", "morning", "mother",
  "mountain", "moved", "movie", "moving", "museum", "myself",
  "napkin", "natural", "nearby", "necessary", "needed",
  "neighbor", "nervous", "never", "night", "nobody",
  "noise", "normal", "nothing", "notice", "number",
  "obviously", "offer", "office", "opened", "opinion",
  "orange", "order", "original", "other", "otherwise",
  "outfit", "outside", "oven",
  "package", "paint", "paper", "parent", "parking",
  "party", "patient", "people", "perfect", "period",
  "permission", "person", "personal", "phone", "photo",
  "picture", "piece", "pizza", "place", "plane", "plate",
  "playing", "please", "plenty", "pocket", "point",
  "police", "popular", "possible", "practice", "prefer",
  "prepare", "present", "pretty", "previous", "price",
  "private", "probably", "problem", "promise", "proud",
  "provide", "public", "pulled", "purpose", "purse",
  "putting",
  "question", "quick", "quickly", "quiet", "quite",
  "rather", "reach", "reading", "ready", "realize",
  "really", "reason", "recently", "recognize", "recommend",
  "refrigerator", "relationship", "relax", "remember",
  "remind", "remove", "repeat", "replace", "report",
  "respect", "restaurant", "return", "right", "round",
  "running",
  "sandwich", "saturday", "scared", "schedule", "school",
  "screen", "search", "season", "secret", "section",
  "serious", "seriously", "service", "several", "shirt",
  "shocked", "shopping", "should", "shower", "sidewalk",
  "similar", "simple", "simply", "since", "sister",
  "situation", "sleep", "slowly", "small", "smell",
  "smile", "smoke", "snack", "social", "someone",
  "something", "sometimes", "somewhere", "sorry", "sound",
  "south", "space", "special", "spend", "sport",
  "stairs", "standing", "started", "station", "still",
  "stomach", "stopped", "store", "story", "straight",
  "strange", "street", "strong", "student", "stuff",
  "stupid", "subject", "suddenly", "suggest", "summer",
  "sunday", "suppose", "surprise", "surprised", "sweater",
  "sweet", "system",
  "table", "taking", "talking", "teacher", "terrible",
  "thank", "thanks", "their", "themselves", "there",
  "thing", "think", "thought", "three", "through",
  "throw", "ticket", "tired", "today", "together",
  "tomorrow", "tonight", "total", "totally", "touch",
  "toward", "traffic", "travel", "treat", "trouble",
  "truck", "trust", "truth", "trying", "tuesday",
  "turned", "twice",
  "uncle", "under", "understand", "unless", "until",
  "upset", "upstairs", "usual", "usually",
  "vacation", "vehicle", "visit", "voice",
  "waiting", "walking", "wallet", "wanted", "warning",
  "washing", "watch", "watching", "water", "wearing",
  "weather", "website", "wedding", "weekend", "weird",
  "welcome", "western", "whatever", "whenever", "whether",
  "while", "whole", "window", "winter", "woman",
  "women", "wonder", "wonderful", "worked", "working",
  "world", "worried", "worry", "worse", "worst",
  "worth", "would", "write", "writing", "wrong",
  "yesterday", "young",
]);

/**
 * Check if a word is a common English word that should not be
 * considered rare/unique for fingerprinting purposes.
 *
 * This checks the frequency dictionary. Words that appear in this
 * dictionary are used frequently enough in everyday English that
 * sharing them is NOT a meaningful stylometric signal.
 */
export function isCommonEnglishWord(word: string): boolean {
  return COMMON_ENGLISH_WORDS.has(word);
}
